aperoRegister:
  is_secure: true

aperoUnsubscribe:
  is_secure: true

account:
  is_secure: true

accountInformations:
  is_secure: true

accountPassword:
  is_secure: true

accountAperos:
  is_secure: true