generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Apero
    theme:                 admin
    css:                    /css/backend.css
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          apero_adminApero
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~

      fields:
        price: { label: Prix }
        is_active: { label: Ouvert }
        location_name: { label: Lieu }
        location_city: { label: Ville }
        date_at: { label: Date }
        time_at: { label: Heure }
        max_people: { label: Max pers. }
        nb_register: { label: Nb participants}

      list:
        display: [date_at, time_at, location_city, location_name, is_active]
        layout: stacked
        params: |
          <p>Le %%date_at%% à %%time_at%% : %%location_city%%, %%location_name%%</p>
          <p>%%is_active%% %%nb_register%% participant(s) / %%max_people%% maximum (%%price%%)</p>
        fields:
          date_at: { date_format: "dd MMMM yyyy" }
          price: { format_currency: "EUR" }
        batch_actions: {}
        
      filter:
        class: false

      form:
        display:
          "Localisation": [ location_name, location_address, location_city, location_zipcode, max_people ]
          "Date": [ date_at, time_at ]
          "Contenu": [ description, price ]
          "Etat": [ is_active ]

      edit:    ~

      new:     ~
