<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/28 19:38:36
sfConfig::add(array(
  'app_max_aperos_on_homepage' => 10,
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
  'app_security_authorized_ip' => array (
  0 => '127.0.0.1',
  1 => '82.245.232.40',
  2 => '88.184.177.103',
  3 => '81.57.23.30',
  4 => '78.229.90.88',
  5 => '85.69.159.191',
),
));
