<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/28 19:38:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=aperophp',
  'username' => 'root',
  'password' => 'Redlight1',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_unicode_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
