<?php
// auto-generated by sfViewConfigHandler
// date: 2011/02/28 19:38:39
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Apéro PHP par l&#039;AFUP', false, false);
  $response->addMeta('keywords', 'apero, rencontre, développement', false, false);
  $response->addMeta('language', 'fr', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('reset.css', '', array ());
  $response->addStylesheet('960.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('/js/jquery/jquery-1.4.2.min.js', '', array ());
  $response->addJavascript('main.js', '', array ());


