<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/02/28 19:38:39
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'superadmin',
    ),
  ),
);
