<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/02/28 19:38:36
$this->security = array (
  'aperoregister' => 
  array (
    'is_secure' => true,
  ),
  'aperounsubscribe' => 
  array (
    'is_secure' => true,
  ),
  'account' => 
  array (
    'is_secure' => true,
  ),
  'accountinformations' => 
  array (
    'is_secure' => true,
  ),
  'accountpassword' => 
  array (
    'is_secure' => true,
  ),
  'accountaperos' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
