<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aperosymfony
 * @subpackage model
 * @author     Benjamin Laugueux <b.laugueux@yzalis.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
  public function getFirstName()
  {
    return $this->getUser()->getFirstName();
  }

  public function getLastName()
  {
    return $this->getUser()->getLastName();
  }

  public function getFullName()
  {
    return $this->getFirstName().' '.mb_strtoupper($this->getLastName(), 'UTF-8');
  }

  public function getEmail()
  {
    return $this->getUser()->getEmailAddress();
  }

  public function getComingAperos()
  {
    return Doctrine_Core::getTable('Apero')->getComingAperosForUser($this->getUser());
  }

  public function getPassedAperos()
  {
    return Doctrine_Core::getTable('Apero')->getPassedAperosForUser($this->getUser());
  }

  public function getAvatarDirectory()
  {
    return 'avatar';
  }

  public function getWelcomeMessage($password)
  {
    $message = Swift_Message::newInstance()
      ->setFrom(array('contact@apero-symfony.com' => 'Apéro symfony'))
      ->setTo($this->getEmail())
      ->setSubject('Bienvenue aux Apéros symfony')
      ->setBody(
<<<EOF
Bonjour {$this->getFirstName()},

Merci de t'être inscrit aux apéros symfony. N'hésite pas à participer et à venir partager avec toute la communauté.

Rappel de tes identifiants :
- email : {$this->getEmail()}
- mot de passe : {$password}

A bientôt,

Benjamin Laugueux
www.apero-symfony.com
EOF
      )
    ;
    return $message;
  }
}
