sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               adminUser
    prefix_path:          /adminUser
    column:               id
    with_wildcard_routes: true

apero_adminApero:
  class: sfDoctrineRouteCollection
  options:
    model:                Apero
    module:               adminApero
    prefix_path:          /adminApero
    column:               id
    with_wildcard_routes: true

# sfDoctrineGuard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_signup:
  url:   /signup
  param: { module: page, action: signUp }

# default rules
homepage:
  url:   /
  param: { module: page, action: homepage }

comingsoon:
  url:   /coming-soon/
  param: { module: page, action: comingSoon }

account:
  url:   /account/
  param: { module: page, action: account }

account_password:
  url:   /account/password/
  param: { module: page, action: accountPassword }

account_informations:
  url:   /account/informations/
  param: { module: page, action: accountInformations }

account_aperos:
  url:   /account/aperos/
  param: { module: page, action: accountAperos }

apero:
  url: /apero/:slug/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: apero }

apero_ics:
  url: /apero/:slug/ics/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: aperoExportIcs }

apero_vcs:
  url: /apero/:slug/vcs/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: aperoExportVcs }

apero_gcal:
  url: /apero/:slug/gcal/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: aperoExportGcal }

apero_register:
  url: /apero/:slug/register/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: aperoRegister }

apero_unsubscribe:
  url: /apero/:slug/unsubscribe/
  class:   sfDoctrineRoute
  options: { model: Apero, type: object }
  param: { module: page, action: aperoUnsubscribe }

contact:
  url:   /contact/
  param: { module: page, action: contact }

concept:
  url:   /concept/
  param: { module: page, action: concept }


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
