# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Apéro PHP par l'AFUP
    #description: symfony project
    keywords:     apero, rencontre, développement
    language:     fr
    robots:       index, follow

  stylesheets:    [reset.css, 960.css, main.css]

  javascripts:    [/js/jquery/jquery-1.4.2.min.js, main.js]

  has_layout:     true
  layout:         layout
