<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aperosymfony
 * @subpackage model
 * @author     Benjamin Laugueux <b.laugueux@yzalis.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew() && $this->username == '')
    {
      $this->setUsername($this->getEmailAddress());
    }
    
    parent::save($conn);
  }
}