#!/usr/bin/env php
<?php

$app = require __DIR__ . '/app.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Aperophp\Database\Tool as DatabaseTool;

$changeEnvironment = function($env) use ($app) {
    $env_config = __DIR__.'/config_'.$env.'.php';

    if(file_exists($env_config)) {
        require $env_config;
    }
};

$console = new Application('Aperophp', '1');

$console->register('db:install')
    ->setDefinition(array(
        new InputOption('env', 'dev', InputOption::VALUE_OPTIONAL, 'Environment'),
        new InputOption('load-fixtures', '', InputOption::VALUE_NONE, 'Import fixtures after database creation'),
    ))
    ->setDescription('Create database')
    ->setHelp('Usage: <info>php app/console db:install [--env=dev] [--load-fixtures]</info>')
    ->setCode(
        function(InputInterface $input, OutputInterface $output) use ($app, $changeEnvironment) {
            $output->writeln('<comment>Env : '.$input->getOption('env').'</comment>');
            $changeEnvironment($input->getOption('env'));

            $databaseTool = new DatabaseTool($app['db']);

            $output->writeln('<info>Create schema.</info>');
            $databaseTool->createSchema(__DIR__ . '/../data/sql/schema.mysql.sql');

            if ($input->getOption('load-fixtures')) {
                $output->writeln('<info>Load fixtures.</info>');
                $databaseTool->loadFixtures(__DIR__.'/../data/sql/fixtures.sql');
            }

            $output->writeln('<info>Installation done.</info>');
        }
);

$console->register('db:load-fixtures')
    ->setDefinition(array(
        new InputOption('env', '', InputOption::VALUE_NONE, 'Environment'),
    ))
    ->setDescription('Create database')
    ->setHelp('Usage: <info>php app/console db:load-fixtures [--env=dev]</info>')
    ->setCode(
        function(InputInterface $input, OutputInterface $output) use ($app, $changeEnvironment) {
            $output->writeln('<comment>Env : '.$input->getOption('env').'</comment>');
            $changeEnvironment($input->getOption('env'));

            $databaseTool = new DatabaseTool($app['db']);

            $output->writeln('<info>Load fixtures</info>');
            $databaseTool->loadFixtures(__DIR__.'/../data/sql/fixtures.sql');
        }
);

$console->run();
