#!/usr/bin/env php
<?php

$app = require __DIR__ . '/app.php';

//Include the namespaces of the components we plan to use
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

$goToEnv = function($env) use ($app) {
    if ('test' === $env) {
        require __DIR__.'/config_test.php';
    } elseif ('travis' === $env) {
        require __DIR__.'/config_travis.php';
    }
};

$importFile = function($file) use ($app) {
    $queries = explode(';', file_get_contents($file));
    foreach ($queries as $query) {
        $query = trim($query);
        if ($query) {
            $app['db']->query($query);
        }
    }
};

$loadFixtures = function() use ($app, $importFile) {
    $importFile(__DIR__.'/../data/sql/fixtures.sql');
};

$console = new Application('Aperophp', '1');

$console->register('db:install')
    ->setDefinition(array(
        new InputOption('env', '', InputOption::VALUE_OPTIONAL, 'Test mode', 'normal'),
        new InputOption('load-fixtures', '', InputOption::VALUE_NONE, 'Test mode'),
    ))
    ->setDescription('Create database')
    ->setHelp('Usage: <info>php app/console db:install [--env=(normal|test|travis)] [--load-fixtures]</info>')
    ->setCode(
        function(InputInterface $input, OutputInterface $output) use ($app, $goToEnv, $importFile, $loadFixtures) {
            $goToEnv($input->getOption('env'));

            $output->writeln('<info>Create schema.</info>');
            $importFile(__DIR__ . '/../data/sql/schema.mysql.sql');

            if ($input->getOption('load-fixtures')) {
                $output->writeln('<info>Load fixtures.</info>');
                $loadFixtures();
            }

            $output->writeln('<info>Installation done.</info>');
        }
);

$console->register('db:load-fixtures')
    ->setDefinition(array(
        new InputOption('test', '', InputOption::VALUE_NONE, 'Test mode'),
    ))
    ->setDescription('Create database')
    ->setHelp('Usage: <info>php app/console db:load-fixtures [--test]</info>')
    ->setCode(
        function(InputInterface $input, OutputInterface $output) use ($app, $goToEnv, $loadFixtures) {
            $goToEnv($input->getOption('env'));

            $loadFixtures();
        }
);

$console->run();
