all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=aperophp
      username: aperophp
      password: aperophp
      encoding: utf8
      attributes:
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8
