all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=name
      username: username
      password: password
      encoding: utf8
      attributes:
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8
